service: GitHubActions

package:
     include:
       - Azure_function.py
     exclude:
       - Azure_function.py

provider:
  name: azure
  runtime: python3.6
  location: westeurope
  
plugins:
  - serverless-azure-functions
  
functions:
  GitHubFunction:
    handler: Azure_function.pipeline_main
    events:
         - http: true
           x-azure-settings:
             authLevel : anonymous
         - http: true
           x-azure-settings:
             direction: out
             name: res
custom:
     webpackIncludeModules:
       packagePath: 'serverless.yml'
