service: GitHubActions

provider:
  name: azure
  runtime: python3.7
  location: westeurope

plugins:
  - serverless-azure-functions
  
functions:
  function1:
    handler: Azure_function.pipeline_main
    runtime: python3.7
    events:
     - http: true
       authLevel: anonymous
     - http: true
       direction: out
          name: res
