service: sls-az-func-rest-api

provider:
  name: azure
  runtime:  python3.7
  region: ${opt:region, 'West EU'}
  stage: ${opt:stage, 'dev'}
  prefix: ${opt:prefix, 'demo'}
  apim: true

plugins:
  - serverless-azure-functions
  - serverless-webpack
functions:
  HelloWorld:
    handler: Azure_function.pipeline_main
    events:
      - http: true
        name: req #<string>, default - "req", specifies which name is available on `context.bindings`
        methods: #<array> [GET, POST, PUT, DELETE], default - all
          - get
        route: Azure_function #<string>, default - <function name>
        authLevel: anonymous #<enum - anonymous|function (default)|admin>
