service: GitHubActions

provider:
  name: azure
  runtime: python3.6
  location: westeurope
  
plugins:
  - serverless-azure-functions
  
functions:
  GitHubFunction:
    handler: Azure_function.pipeline_main
